package com.mirror.mirror.ui.theme

import androidx.compose.ui.graphics.Color

val MirrorPrimaryLight = Color(0xFF7155B7)
val MirrorOnPrimaryLight = Color(0xFFFFFFFF)
val MirrorPrimaryContainerLight = Color(0xFFE8DDFF)
val MirrorOnPrimaryContainerLight = Color(0xFF280061)
val MirrorSecondaryLight = Color(0xFF655E77)
val MirrorOnSecondaryLight = Color(0xFFFFFFFF)
val MirrorSecondaryContainerLight = Color(0xFFE9DFF8)
val MirrorOnSecondaryContainerLight = Color(0xFF21182F)
val MirrorTertiaryLight = Color(0xFF8E5268)
val MirrorOnTertiaryLight = Color(0xFFFFFFFF)
val MirrorTertiaryContainerLight = Color(0xFFFFD9E4)
val MirrorOnTertiaryContainerLight = Color(0xFF3A071E)
val MirrorErrorLight = Color(0xFFBA1A1A)
val MirrorOnErrorLight = Color(0xFFFFFFFF)
val MirrorErrorContainerLight = Color(0xFFFFDAD6)
val MirrorOnErrorContainerLight = Color(0xFF410002)
val MirrorBackgroundLight = Color(0xFFFFFBFF)
val MirrorOnBackgroundLight = Color(0xFF1D1B20)
val MirrorSurfaceLight = Color(0xFFFFFBFF)
val MirrorOnSurfaceLight = Color(0xFF1D1B20)
val MirrorSurfaceVariantLight = Color(0xFFE7E0EC)
val MirrorOnSurfaceVariantLight = Color(0xFF49454F)
val MirrorOutlineLight = Color(0xFF7A757F)
val MirrorOutlineVariantLight = Color(0xFFCAC4D0)

val MirrorPrimaryDark = Color(0xFFD1BCFF)
val MirrorOnPrimaryDark = Color(0xFF3B1E78)
val MirrorPrimaryContainerDark = Color(0xFF54379F)
val MirrorOnPrimaryContainerDark = Color(0xFFE8DDFF)
val MirrorSecondaryDark = Color(0xFFCDC2DB)
val MirrorOnSecondaryDark = Color(0xFF362D47)
val MirrorSecondaryContainerDark = Color(0xFF4D435F)
val MirrorOnSecondaryContainerDark = Color(0xFFE9DFF8)
val MirrorTertiaryDark = Color(0xFFFFB0C8)
val MirrorOnTertiaryDark = Color(0xFF561D33)
val MirrorTertiaryContainerDark = Color(0xFF713348)
val MirrorOnTertiaryContainerDark = Color(0xFFFFD9E4)
val MirrorErrorDark = Color(0xFFFFB4AB)
val MirrorOnErrorDark = Color(0xFF690005)
val MirrorErrorContainerDark = Color(0xFF93000A)
val MirrorOnErrorContainerDark = Color(0xFFFFDAD6)
val MirrorBackgroundDark = Color(0xFF141217)
val MirrorOnBackgroundDark = Color(0xFFE7E1E8)
val MirrorSurfaceDark = Color(0xFF141217)
val MirrorOnSurfaceDark = Color(0xFFE7E1E8)
val MirrorSurfaceVariantDark = Color(0xFF49454F)
val MirrorOnSurfaceVariantDark = Color(0xFFCAC4D0)
val MirrorOutlineDark = Color(0xFF948F99)
val MirrorOutlineVariantDark = Color(0xFF49454F)
